# Generated by Django 6.0.2 on 2026-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='tracks/')),
                ('emotion', models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('neutral', 'neutral'), ('disgust', 'disgust'), ('angry', 'angry'), ('surprised', 'surprised'), ('fear', 'fear')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
