# Generated by Django 5.2.11 on 2026-02-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='emotion',
            field=models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('neutral', 'neutral'), ('disgust', 'disgust'), ('angry', 'angry'), ('surprised', 'surprised'), ('fearful', 'fearful'), ('calm', 'calm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
